version: '3.8'

services:
  wellness-ping:
    image: micr0dev/wellness-ping:latest
    container_name: wellness-ping
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - wellness_ping_data:/app/data

volumes:
  wellness_ping_data:
