version: '3.8'

services:
  wellness-ping-debug:
    image: node:18-alpine
    container_name: wellness-ping-debug
    restart: no
    working_dir: /app
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - wellness_ping_data:/app/data
    command: >
      sh -c "
        apk add --no-cache git &&
        echo '=== CLONING REPOSITORY ===' &&
        git clone -b main --depth 1 https://github.com/micr0-dev/wellness-ping.git /tmp/wellness &&
        echo '=== REPOSITORY STRUCTURE ===' &&
        find /tmp/wellness -type f -name '*.json' -o -name '*.js' -o -name '*.ts' | head -20 &&
        echo '=== ROOT DIRECTORY CONTENTS ===' &&
        ls -la /tmp/wellness/ &&
        echo '=== PACKAGE.JSON IF EXISTS ===' &&
        if [ -f '/tmp/wellness/package.json' ]; then
          cat /tmp/wellness/package.json
        else
          echo 'NO PACKAGE.JSON IN ROOT'
        fi &&
        # Copier pour inspection manuelle
        cp -r /tmp/wellness/* /app/ &&
        echo '=== APP DIRECTORY NOW ===' &&
        ls -la /app/ &&
        echo '=== DEBUG COMPLETE ===' &&
        sleep 3600
      "

volumes:
  wellness_ping_data:
