version: '3.8'

services:
  wellness-ping:
    build: https://github.com/micr0-dev/wellness-ping.git
    container_name: wellness-ping
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - wellness_ping_data:/app/data

volumes:
  wellness_ping_data:
