version: '3.8'

services:
  wellness-ping:
    image: node:18-alpine
    container_name: wellness-ping
    restart: unless-stopped
    working_dir: /app
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - wellness_ping_data:/app/data
    command: >
      sh -c "
        apk add --no-cache git &&
        git clone https://github.com/micr0-dev/wellness-ping.git /app &&
        npm install &&
        npm run build &&
        npm start
      "

volumes:
  wellness_ping_data:
